import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Legal solutions',
  description: 'Generated by create next app',
};

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="bg-light dark:bg-gray-700">{children}</main>
      </body>
    </html>
  );
}
