import type { Metadata } from "next";
import CustomSidebar from "./components/sidebar/sidebar";

export const metadata: Metadata = {
  title: "Legal solutions – admin dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className="h-full flex">
      <CustomSidebar />

      <div className="sm:p-4 ml-16 bg-white h-full w-full overflow-hidden">
        <div className="p-4 rounded-lg dark:border-gray-700 overflow-auto">
          {children}
        </div>
      </div>
    </section>
  );
}
