import type { Metadata } from "next";
import CustomSidebar from "./components/sidebar/sidebar";

export const metadata: Metadata = {
  title: "Legal solutions – admin dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className="flex h-full">
      <CustomSidebar />

      <div className="dashboard__layout-bg">
        <div className="p-4 overflow-auto rounded-lg dark:border-gray-700">
          {children}
        </div>
      </div>
    </section>
  );
}
