import type { Metadata } from "next";
import CustomSidebar from "./components/sidebar/sidebar";

export const metadata: Metadata = {
  title: "Legal solutions – admin dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className="h-full flex">
      <CustomSidebar />

      <div className="p-4 bg-white h-full w-full">
        <div className="p-4 border-2 border-gray-200 border-dashed rounded-lg dark:border-gray-700">
          {children}
        </div>
      </div>
    </section>
  );
}
